#
# Module manifest for module 'PSADInfoGet'
#
# Generated by: Hong Li
#
# Generated on: 01/09/2019
#

@{
    RootModule = 'PSADInfoGet.psm1'
    ModuleVersion = '1.0.0'
    GUID = '88f3c108-33ec-4120-9e97-6a5b2c041d8f'
    Author = 'Hong Li'
    Copyright = '(c) 2019 Hong Li. All rights reserved.'
    Description = 'PSADInfoGet provides commands for getting information from active directory'
    PowerShellVersion = '5.1'

    FormatsToProcess = @('Format\ADUserInfo.Format.ps1xml', 'Format\ADGroupInfo.Format.ps1xml')

    FunctionsToExport = @('Get-ADUserInfo', 'Get-ADGroupInfo', 'Set-ADInfoConfig', 'Get-ADInfoConfig')
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @('aduser', 'adu', 'adgroup', 'adg')

	PrivateData = @{
        PSData = @{
            Tags         = 'PowerShell', 'Active Directory', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows'
			LicenseUri   = 'https://github.com/hongstack/PSADInfoGet/blob/master/LICENSE'
			ProjectUri   = 'https://github.com/hongstack/PSADInfoGet'
            ReleaseNotes = 'https://github.com/hongstack/PSADInfoGet/releases/tag/1.0.0'
        }
    }
}